# Site settings
title: Life in Motion
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Reza's personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rezasalari
github_username:  resal81

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
